# Generated by Django 5.2.16 on 2026-07-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('identifikator', models.CharField(max_length=50, unique=True)),
                ('havolalar', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
