# Generated by Django 5.2.16 on 2026-07-31 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kanal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('video', models.FileField(upload_to='videos/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ochiqligi', models.CharField(choices=[('public', 'Hammaga ochiq'), ('unlisted', 'Havola orqali'), ('private', 'Maxfiy')], default='public', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kanal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='kanal.kanal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
